### ISSUE TITLE
Allow request body to be representable as a JSON

### ISSUE THREAD

**Issue by emmberk** [connexta/ion-ingest-api#5]
https://github.com/connexta/ion-ingest-api/pull/4 updated the API to fix a bug in the code generation that caused the generated endpoint to return a 415 status code. The goal of this task is to revert that change and address the issue. See https://github.com/connexta/ion-ingest-api/pull/4#issuecomment-497415539.

This issue should be completed before the first release of the API.

**Comment by lessarderic** [comment]
@emmberk, do you remember what the issue was here? Looking back at how multipart messages should be defined, it looks like what we have right now is ok and we shouldn't need to make any changes.

**Comment by jhunzik** [comment]
@lessarderic, right now we stick each String in a separate part of the request. I would think we would only need two parts: a JSON body with all of metadata and the actual file. I'd have to do some digging to if/when the generators got fixed.

**Comment by lessarderic** [comment]
Ah! I knew I was forgetting something. Thanks for reminding me.

**Comment by jhunzik** [comment]
Now that we removed the extra parameters, we are only left with the Accept-Version header and a file. This isn't an issue anymore.
